import numpy as np
import pinocchio as pin

from go2_control.model import(
    build_go2_model,
    nominal_configuration,
)

np.set_printoptions(
    precision=10,
    suppress=False,
)

model = build_go2_model()
q = nominal_configuration(model)

rng = np.random.default_rng(7)

velocity = rng.normal(
    scale=0.1,
    size=model.nv
)

desired_acceleration = rng.normal(
    scale=0.2,
    size=model.nv,
)

# ============================================================
# 1. 使用 RNEA：由期望加速度求广义力
# ============================================================
rnea_data = model.createData()

generalized_force = pin.rnea(
    model,
    rnea_data,
    q,
    velocity,
    desired_acceleration,
).copy()

# ============================================================
# 2. 使用 ABA：由广义力反求加速度
# ============================================================

aba_data = model.createData()

acceleration_from_aba = pin.aba(
    model,
    aba_data,
    q,
    velocity,
    generalized_force,
).copy()

aba_error = (
    acceleration_from_aba - desired_acceleration
)

# ============================================================
# 3. 使用动力学方程直接求加速度
# ============================================================

crba_data = model.createData()

mass_matrix_upper = pin.crba(
    model,
    crba_data,
    q
).copy()

mass_matrix = (
    np.triu(mass_matrix_upper) + np.triu(mass_matrix_upper, k=1).T
)

nonlinear_data = model.createData()

nonlinear_effects = pin.nonLinearEffects(
    model,
    nonlinear_data,
    q,
    velocity,
).copy()
#惯性项
right_hand_side = (
    generalized_force - nonlinear_effects
)

acceleration_from_equation = np.linalg.solve(
    mass_matrix,
    right_hand_side,
)

equation_error = (
    acceleration_from_equation - desired_acceleration
)

# ============================================================
# 4. 无外力时的自由落体
# ============================================================

zero_velocity =np.zeros(model.nv)
zero_generalized_force = np.zeros(model.nv)

free_fall_data = model.createData()

free_fall_acceleration = pin.aba(
    model,
    free_fall_data,
    q,
    zero_velocity,
    zero_generalized_force
).copy()

# ============================================================
# 5. 输出结果
# ============================================================

print("Desired generalized acceleration:")
print(desired_acceleration)

print("\nGeneralized force generated by RNEA:")
print(generalized_force)

print("\nAcceleration recovered by ABA:")
print(acceleration_from_aba)

print("\nABA acceleration error:")
print(aba_error)

print("\nABA error norm:")
print(np.linalg.norm(aba_error))

print("\nAcceleration recovered by solving M*a = tau-h:")
print(acceleration_from_equation)

print("\nEquation error norm:")
print(np.linalg.norm(equation_error))

print("\nFree-fall base acceleration:")
print(free_fall_acceleration[:6])

print("\nFree-fall joint acceleration:")
print(free_fall_acceleration[6:])

print("\nFree-fall joint acceleration norm:")
print(
    np.linalg.norm(
        free_fall_acceleration[6:]
    )
)