<?xml version="1.0"?>
<package format="3">
  <name>go2_mpc_bridge</name>
  <version>0.1.0</version>
  <description>OCS2 MRT integration for Go2 locomotion control.</description>

  <maintainer email="648749943@qq.com">CanggouBaiyun</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>boost</depend>
  <depend>ocs2_ros_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>